/*
 * This Groovy source file was generated by the Gradle 'init' task.
 */
class App {

    LogicService ls = new LogicService()

    def start(int first, int second) {
        def results = ["first":ls.isFirstNumberBigger(first, second),
                        "second":ls.isSecondNumberBigger(first, second)]
        return results
    }

    static void main(String[] args) {
        int[] params = parseInput(args)
        App app = new App()
        app.start(params[0], params[1])
    }

    static int[] parseInput(String[] args)
    {
        def numbers = []
        args.each {
            if(it.isNumber())numbers.add it.toInteger()
        }
        if(numbers.size()==0) numbers = [1,2]
        return numbers as int[]
    }

    def dummyMethod(String a) {
        println a.size()
    }


}
